### ISSUE TITLE
Error: Class 'CanadaPost\Rating' not found

### ISSUE THREAD

**Issue by ademahendra** [thejacer87/commerce_canadapost#19]
Error: Class 'CanadaPost\Rating' not found in Drupal\commerce_canadapost\Api\RatingService->getRequest() (line 99 of /web/modules/contrib/commerce_canadapost/src/Api/RatingService.php).

Error happen when requesting quotes

**Comment by thejacer87** [comment]
have you opened an issue in the drupal module page? might be more appropriate over there
